package sjsu.edu.cs218project2.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "patient")
public class Patient {

    @DynamoDBHashKey(attributeName = "patient_id")
    @DynamoDBAutoGeneratedKey
    private String patient_id;

    @DynamoDBAttribute(attributeName = "gender")
    private String gender;

    @DynamoDBAttribute(attributeName = "polyuria")
    private Integer polyuria;

    @DynamoDBAttribute(attributeName = "polydipsia")
    private Integer polydipsia;

    @DynamoDBAttribute(attributeName = "weight_loss")
    private Integer weight_loss;

    @DynamoDBAttribute(attributeName = "weakness")
    private Integer weakness;

    @DynamoDBAttribute(attributeName = "polyphagia")
    private Integer polyphagia;

    @DynamoDBAttribute(attributeName = "genital_thrush")
    private Integer genital_thrush;

    @DynamoDBAttribute(attributeName = "visual_blurring")
    private Integer visual_blurring;

    @DynamoDBAttribute(attributeName = "itching")
    private Integer itching;



}
