package sjsu.edu.cs218project2.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "patient")
public class Patient {

    @DynamoDBHashKey(attributeName = "patient_id")
    @DynamoDBAutoGeneratedKey
    private String patientId;

    @DynamoDBAttribute(attributeName = "firstname")
    private String firstname;

    @DynamoDBAttribute(attributeName = "lastname")
    private String lastname;

    @DynamoDBAttribute(attributeName = "age")
    private Integer age;

    @DynamoDBAttribute(attributeName = "height")
    private Integer height;

    @DynamoDBAttribute(attributeName = "weight")
    private Integer weight;

//    @DynamoDBAttribute(attributeName = "diagnose")
//    private Diagnose diagnose;

    public Patient() {

    }

    public Patient(String patientId, String firstname, String lastname, Integer age, Integer height, Integer weight) {
        this.patientId = patientId;
        this.firstname = firstname;
        this.lastname = lastname;
        this.age = age;
        this.height = height;
        this.weight = weight;
//        this.diagnose = diagnose;
    }

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

//    public Diagnose getDiagnose() {
//        return diagnose;
//    }
//
//    public void setDiagnose(Diagnose diagnose) {
//        this.diagnose = diagnose;
//    }
}
