//“SJSU CS 218 Spring 2021 TEAM3”
package sjsu.edu.cs218project2.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "patient")
public class Patient {


    @DynamoDBHashKey(attributeName = "email")
    @DynamoDBAutoGeneratedKey
    private String email;

    @DynamoDBAttribute(attributeName = "patient_id")
    private String patient_id;

    @DynamoDBAttribute(attributeName = "dob")
    private String dob;

    @DynamoDBAttribute(attributeName = "gender")
    private Integer gender;

    @DynamoDBAttribute(attributeName = "polyuria")
    private Integer polyuria;

    @DynamoDBAttribute(attributeName = "alopecia")
    private Integer alopecia;

    @DynamoDBAttribute(attributeName = "irritability")
    private Integer irritability;

    @DynamoDBAttribute(attributeName = "muscle_stiffness")
    private Integer muscle_stiffness;

    @DynamoDBAttribute(attributeName = "polydipsia")
    private Integer polydipsia;

    @DynamoDBAttribute(attributeName = "weight_loss")
    private Integer weight_loss;

    @DynamoDBAttribute(attributeName = "weakness")
    private Integer weakness;

    @DynamoDBAttribute(attributeName = "polyphagia")
    private Integer polyphagia;

    @DynamoDBAttribute(attributeName = "genital_thrush")
    private Integer genital_thrush;

    @DynamoDBAttribute(attributeName = "visual_blurring")
    private Integer visual_blurring;

    @DynamoDBAttribute(attributeName = "delayed_healing")
    private Integer delayed_healing;

    @DynamoDBAttribute(attributeName = "partial_paresis")
    private Integer partial_paresis;

    @DynamoDBAttribute(attributeName = "itching")
    private Integer itching;

    @DynamoDBAttribute(attributeName = "obesity")
    private Integer obesity;

}
