//SJSU CS 218 Spring 2021 TEAM3
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:b604434f-0858-42f8-98c9-9f3cb41e6e12",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_XOJ7AWdQN",
    "aws_user_pools_web_client_id": "7rf000s28l6gvs79tvpvqp6qe3",
    "oauth": {}
};


export default awsmobile;
